### ISSUE TITLE
install by composer does  not work

### ISSUE THREAD

**Issue by camiloreynaga** [Vilochane/yii2-barcode-generator-8-types#1]
the install by composer does not work, after try install throw the message: 

Problem 1
    - The requested package vilochane/yii2-barcode-generator could not be found
in any version, there may be a typo in the package name.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your min
  imum-stability setting
  see https://getcomposer.org/doc/04-schema.md#minimum-stability for more det
  ails.

**Comment by Vilochane** [comment]
Hello Camil, I apologize for the late reply, please try : "vilochane/yii2-barcode-generator": "*", in your composer.

**Comment by veronicavg** [comment]
Hello,
I have the same problem. With the * I get:

> 
> Problem 1
>     - The requested package vilochane/yii2-barcode-generator * is satisfiable by vilochane/yii2-barcode-generator[dev-master] but these conflict with your requirements or minimum-stability.

My composer.json:

`"minimum-stability": "stable",`

Can you help me?
