### ISSUE TITLE
installation faild via composer

### ISSUE THREAD

**Issue by miladhashemi** [Vilochane/yii2-barcode-generator-8-types#6]
When I try to install this plugin through composer command, bellow message appear in cmd:

 [InvalidArgumentException]
  Could not find package dev-master at any version for your minimum-stability
   (stable). Check the package spelling or your minimum-stability

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...

**Comment by Vilochane** [comment]
Can you let me know your php version

**Comment by miladhashemi** [comment]
Sure
PHP 7.0.9
I think the command format that written  in yii2 extension wasn't right.
 http://www.yiiframework.com/extension/yii2-barcode-generator-8-types/
At first I don't look carefully.  After correct the command the package installed.
Thank You.

**Comment by Vilochane** [comment]
@miladhashemi: Happy it worked out for you. Cheers
